CsteOverflow/urls.py
from re import template
from django.contrib import admin
from django.urls import path, include
from csteusers import views as user_view
from django.contrib.auth import views as auth_view
from django.conf import settings
from django.conf.urls.static import static
from cstebase import views
from csteusers.views import *
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('cstebase.urls')),
    
    # Authentication System
    # path('register/',user_view.register,name='register'),
    # path('login/',auth_view.LoginView.as_view(template_name='csteusers/login.html'),name='login'),
    path('logout/',auth_view.LogoutView.as_view(template_name='csteusers/logout.html'),name='logout'),
    
    #email authentications
    path('signup/',user_view.signup,name='signup'),
    path('signin/',user_view.signin,name='signin'),
    path('activate/<uidb64>/<token>',activate,name='activate'),
    
    # Profile 
    path('profile/',user_view.profile,name= "profile" ),
    path('profile/update',user_view.profile_update,name= "profile_update" ),
    # path('ckeditor/', include('ckeditor_uploader.urls')),
    # path('authentication/',include('csteusers.urls'))
    
    
    
] 
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

cstebase/urls.py
from re import template
from django.urls import path
from . import views



app_name = 'cstebase'

urlpatterns = [
    path('',views.Home.as_view(),name='home'),
    
    
    # CRUD Function
    path('questions/',views.QuestionListView.as_view(),name='question-lists'),
    path('questions/new/',views.QuestionCreateView.as_view(),name='question-create'),
    path('questions/<int:pk>',views.questionDetailedView,name='question-detail'),
    path('questions/<int:pk>/update',views.QuestionUpdateView.as_view(),name='question-update'),
    path('answered/<int:pk1>/<int:pk>',views.answeredQuestion,name='answered-question'),

    path('questions/<int:pk>/delete',views.QuestionDeleteView.as_view(),name='question-delete'),
    path('questions/<int:pk>/comment',views.AddCommentView,name='question-comment'),
    path('questions/<int:pk>/edit-answer/<int:comment_id>',views.EditCommentView,name='EditCommentView'),
    path('questions/<int:pk>/delete-answer/<int:comment_id>',views.DeleteCommentView,name='DeleteCommentView'),
    # path('questions/<int:pk>/comment',views.AddCommentView.as_view(),name='question-comment'),
    path('like/<int:pk>', views.like_view, name="like_post"),
    path('showprofile/<str:str>', views.ShowProfile,name='show_profile'),
    path('questions-all/<str:str>', views.ShowAllQuestionProfileBased,name='ShowAllQuestionProfileBased'),
    #path('all-question', views.ShowAllQuestionProfileBased, name="ShowAllQuestionProfileBased"),
    path('about/',views.About_page,name='about'),
    path('tags/<slug:tag_slug>',views.TagListView.as_view(),name="post_tag"),
    # path('test/',views.test.as_view(),name="test"),
    path('tags/',views.AllTags,name="tags"),
    path('questions/search/',views.search,name='search'),
]
    

    

csteusers/models.py
from email.policy import default
from pyexpat import model
from tkinter import CASCADE
from django.db import models
from django.contrib.auth.models import User
from PIL import Image
# from phonenumber_field.modelfields import PhoneNumberField

class Profile(models.Model):
     user = models.OneToOneField(User,on_delete=models.CASCADE)
     first_name = models.CharField(max_length=100,null=True,blank=True)
     last_name = models.CharField(max_length=100,null=True,blank=True)
     birthday =  models.DateField(blank=True, null=True)
     bio = models.CharField( max_length= 150)
     phone = models.IntegerField(blank=True, null=True) 
     image = models.ImageField(default ='default.jpg',  upload_to="images/profile")
     linkedIn= models.CharField( max_length=50,null=True,blank=True)
     
     
     def __str__(self):
         return f'{self.user.username} - Profile'
     
     
     def save(self, *args, **kwargs):
         super().save(*args, **kwargs)
         img = Image.open(self.image.path)
         if img.height > 300 or img.width > 300:
                output_size = (300, 300)
                img.thumbnail(output_size)
                img.save(self.image.path)
     
     
     
     

csteusers/forms.py
from dataclasses import fields
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.db import models
from .models import Profile
# from django.forms import extras


class UserRegisterForm(UserCreationForm):
    email = forms.EmailField
    # email = forms.CharField()
    #password1 = forms.CharField
    #password2 = forms.PasswordInput()
    # password2 = forms.PasswordInput
    # password1_address = forms.EmailField( 
    #     label="Please enter your email address",
    #   )
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']
        widgets = {
            #'email': forms.EmailField()
            #'email':forms.EmailInput(attrs={'class': 'form-control','placeholder':'Enter your email'}),
              'email': forms.TextInput(attrs={'class': 'form-control','placeholder':'Enter your email'}),
              'username': forms.TextInput(attrs={'class': 'form-control','placeholder':'Enter Unique username'}),
             #'password1': forms.CharField(),
             #'password1': forms.TextInput(attrs={'class': 'form-control','placeholder':'Enter Password'}),
            #   'password2':forms.Textarea(attrs={'class': 'form-control','placeholder':'Enter your Password'})
            #   'password2': forms.TextInput(attrs={'class': 'form-control','placeholder':'Confirm Password'}),
 
        }

class UserUpdateForm(forms.ModelForm):
     email = forms.EmailField()
     
     class Meta:
          model = User
          fields = ['username','email'] 
          
          
          
class DateInput(forms.DateInput):
    input_type = 'date'


class ProfileUpdateForm(forms.ModelForm):
     birthday =  forms.DateField(widget=DateInput)
     class Meta:
          model = Profile
          fields = ['first_name','last_name','birthday','bio','phone','linkedIn']
          widgets = {
              'birthday':DateInput(attrs={'class': 'form-control'}),
          }
          
class ProfileImageForm(forms.ModelForm):
     class Meta:
          model = Profile
          fields = ['image']
          

csteusers/views.py
from ast import And
from django.shortcuts import render,redirect ,get_object_or_404,HttpResponseRedirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from .forms import UserRegisterForm,UserUpdateForm,ProfileUpdateForm,ProfileImageForm
from django.contrib.auth.decorators import login_required
from django.views.generic import *
from .models import Profile



def register(request):
    if request.method == "POST":
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f'Account Successfully created for {username}! Login In Now')
            return redirect('login')
    else:
        form = UserRegisterForm()

    return render(request, 'csteusers/register.html', {'form': form})

@login_required
def profile(request):
     return render(request,'csteusers/profile.html')


@login_required
def profile_update(request):
    obj = get_object_or_404(Profile, id = request.user.profile.id)
    form1 = ProfileImageForm(request.POST or None , request.FILES,  instance = obj)
    if request.method == "POST":
        
        form = ProfileUpdateForm(request.POST or None ,  instance = obj)
       
        if form.is_valid() and form1.is_valid():
            form.save()
            form1.save()
            messages.success(request, f'Acount Updated Successfully!')
            return redirect('profile')
    else:

        form = ProfileUpdateForm(request.POST or None,  instance = obj)
    context = {
        'p_form': form,
        'image_form': form1,
        
    }
    return render(request, 'csteusers/profile_update.html', context)



#Email Authentications



from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth.models import User
from django.contrib import messages
from django.core.mail import EmailMessage, send_mail
from CsteOverflow import settings
from django.contrib.sites.shortcuts import get_current_site
from django.template.loader import render_to_string
from django.utils.http import urlsafe_base64_decode, urlsafe_base64_encode
from django.utils.encoding import *
from django.contrib.auth import authenticate, login, logout
from . tokens import generate_token
# from django.utils.encoding import force_text
from django.utils.encoding import force_str
import django
from django.utils.encoding import force_str
django.utils.encoding.force_text = force_str

def signup(request):
     
     if request.method =='POST':

          email = request.POST['email']
          pass1 = request.POST['pass1']
          pass2 = request.POST['pass2']
          
          username = email.split("@")[0]
          
          
          
          if User.objects.filter(email=email).exists():
            messages.warning(request, "Email Already Registered!!")
            return redirect('signup')
       

          if pass1 != pass2:
               messages.info(request, "Passwords didn't matched!!")
               return redirect('signup')

          if not username.isalnum():
               messages.error(request, "Username must be Alpha-Numeric!!")
               return redirect('home')       
          myuser = User.objects.create_user(username, email, pass1)

          # myuser.is_active = False
          myuser.is_active = False
          myuser.save()
          messages.success(request, "Your Account has been created succesfully!! Please check your email to confirm your email address in order to activate your account.")
          
          # Welcome Email
          subject = "Welcome to CSTEOVERFLOW "
          message = "Hello " + myuser.first_name + "!! \n" + "Welcome to CSTEOVERFLOW!! \nThank you for visiting our website\n. We have also sent you a confirmation email, please confirm your email address."        
          from_email = settings.EMAIL_HOST_USER
          to_list = [myuser.email]
          send_mail(subject, message, from_email, to_list, fail_silently=True)
          
          
        # Email Address Confirmation Email
          current_site = get_current_site(request)
          email_subject = "Confirm your Email @ CSTEOVERFLOW "
          message2 = render_to_string('email_confirmation.html',{
               
               'name': myuser.first_name,
               'domain': current_site.domain,
               'uid': urlsafe_base64_encode(force_bytes(myuser.pk)),
               'token': generate_token.make_token(myuser)
          })
          email = EmailMessage(
               email_subject,
               message2,
               settings.EMAIL_HOST_USER,
               [myuser.email],
          )
          email.fail_silently = True
          email.send()
          
          return redirect('signin')          
            
     
     return render(request,'authentication/signup.html')

def signin(request):
     if request.method == 'POST':
          username = request.POST['username']
          pass1 = request.POST['pass1']
          
          user = authenticate(username = username,password=pass1)
          
          if user is not None:
               login(request, user)
               fname = user.first_name
               # messages.success(request, "Logged In Sucessfully!!")
               return redirect('cstebase:home')

          else:
               messages.info(request, "Bad Credentials!!")
               return redirect('signin')
               
          
     
     return render(request,'authentication/signin.html')


     
     
def activate(request,uidb64,token):
     try:
          uid = force_str(urlsafe_base64_decode(uidb64))
          myuser = User.objects.get(pk=uid)
     except(TypeError,ValueError,OverflowError,User.DoesNotExist):
          myuser = None
     
     if myuser is not None and generate_token.check_token(myuser,token):
          myuser.is_active = True
          myuser.save()
          login(request,myuser)
          return redirect('cstebase:home')
     else:
          return render(request,'activation_fails.html')
     
     

csteusers/templates/csteusers/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
        @import url('https://fonts.googleapis.com/css?family=Poppins');

/* BASIC */

html {
  background-color: #e7e7e7;
  background: linear-gradient(200deg, yellow 0%, rgb(236, 146, 0) 100%);
}

body {
  font-family: "Poppins", sans-serif;
  height: 100vh;
}

a {
  color: #92badd;
  display:inline-block;
  text-decoration: none;
  font-weight: 400;
}

h2 {
  text-align: center;
  font-size: 16px;
  font-weight: 600;
  text-transform: uppercase;
  display:inline-block;
  margin: 40px 8px 10px 8px; 
  color: #cccccc;
}



/* STRUCTURE */

.wrapper {
  display: flex;
  align-items: center;
  flex-direction: column; 
  justify-content: center;
  width: 100%;
  min-height: 100%;
  padding: 20px;
}

#formContent {
  -webkit-border-radius: 10px 10px 10px 10px;
  border-radius: 10px 10px 10px 10px;
  background: #fff;
  padding: 30px;
  width: 90%;
  max-width: 450px;
  position: relative;
  padding: 0px;
  -webkit-box-shadow: 0 30px 60px 0 rgba(0,0,0,0.3);
  box-shadow: 0 30px 60px 0 rgba(0,0,0,0.3);
  text-align: center;
}

#formFooter {
  background-color: #f6f6f6;
  border-top: 1px solid #dce8f1;
  padding: 25px;
  text-align: center;
  -webkit-border-radius: 0 0 10px 10px;
  border-radius: 0 0 10px 10px;
}



/* TABS */

h2.inactive {
  color: #cccccc;
}

h2.active {
  color: #0d0d0d;
  border-bottom: 2px solid #5fbae9;
}



/* FORM TYPOGRAPHY*/

input[type=button], input[type=submit], input[type=reset]  {
  background-color: #56baed;
  border: none;
  color: white;
  padding: 15px 80px;
  text-align: center;
  text-decoration: none;
  display: inline-block;
  text-transform: uppercase;
  font-size: 13px;
  -webkit-box-shadow: 0 10px 30px 0 rgba(95,186,233,0.4);
  box-shadow: 0 10px 30px 0 rgba(95,186,233,0.4);
  -webkit-border-radius: 5px 5px 5px 5px;
  border-radius: 5px 5px 5px 5px;
  margin: 5px 20px 40px 20px;
  -webkit-transition: all 0.3s ease-in-out;
  -moz-transition: all 0.3s ease-in-out;
  -ms-transition: all 0.3s ease-in-out;
  -o-transition: all 0.3s ease-in-out;
  transition: all 0.3s ease-in-out;
}

input[type=button]:hover, input[type=submit]:hover, input[type=reset]:hover  {
  background-color: #39ace7;
}

input[type=button]:active, input[type=submit]:active, input[type=reset]:active  {
  -moz-transform: scale(0.95);
  -webkit-transform: scale(0.95);
  -o-transform: scale(0.95);
  -ms-transform: scale(0.95);
  transform: scale(0.95);
}

input[type=text] {
  background-color: #f6f6f6;
  border: none;
  color: #0d0d0d;
  padding: 10px 32px;
  text-align: center;
  text-decoration: none;
  display: inline-block;
  font-size: 16px;
  margin: 5px;
  width: 85%;
  border: 2px solid #f6f6f6;
  -webkit-transition: all 0.5s ease-in-out;
  -moz-transition: all 0.5s ease-in-out;
  -ms-transition: all 0.5s ease-in-out;
  -o-transition: all 0.5s ease-in-out;
  transition: all 0.5s ease-in-out;
  -webkit-border-radius: 5px 5px 5px 5px;
  border-radius: 5px 5px 5px 5px;
}

input[type=text]:focus {
  background-color: #fff;
  border-bottom: 2px solid #5fbae9;
}

input[type=text]:placeholder {
  color: #cccccc;
}



/* ANIMATIONS */

/* Simple CSS3 Fade-in-down Animation */
.fadeInDown {
  -webkit-animation-name: fadeInDown;
  animation-name: fadeInDown;
  -webkit-animation-duration: 1s;
  animation-duration: 1s;
  -webkit-animation-fill-mode: both;
  animation-fill-mode: both;
}

@-webkit-keyframes fadeInDown {
  0% {
    opacity: 0;
    -webkit-transform: translate3d(0, -100%, 0);
    transform: translate3d(0, -100%, 0);
  }
  100% {
    opacity: 1;
    -webkit-transform: none;
    transform: none;
  }
}

@keyframes fadeInDown {
  0% {
    opacity: 0;
    -webkit-transform: translate3d(0, -100%, 0);
    transform: translate3d(0, -100%, 0);
  }
  100% {
    opacity: 1;
    -webkit-transform: none;
    transform: none;
  }
}

/* Simple CSS3 Fade-in Animation */
@-webkit-keyframes fadeIn { from { opacity:0; } to { opacity:1; } }
@-moz-keyframes fadeIn { from { opacity:0; } to { opacity:1; } }
@keyframes fadeIn { from { opacity:0; } to { opacity:1; } }

.fadeIn {
  opacity:0;
  -webkit-animation:fadeIn ease-in 1;
  -moz-animation:fadeIn ease-in 1;
  animation:fadeIn ease-in 1;

  -webkit-animation-fill-mode:forwards;
  -moz-animation-fill-mode:forwards;
  animation-fill-mode:forwards;

  -webkit-animation-duration:1s;
  -moz-animation-duration:1s;
  animation-duration:1s;
}

.fadeIn.first {
  -webkit-animation-delay: 0.4s;
  -moz-animation-delay: 0.4s;
  animation-delay: 0.4s;
}

.fadeIn.second {
  -webkit-animation-delay: 0.6s;
  -moz-animation-delay: 0.6s;
  animation-delay: 0.6s;
}

.fadeIn.third {
  -webkit-animation-delay: 0.8s;
  -moz-animation-delay: 0.8s;
  animation-delay: 0.8s;
}

.fadeIn.fourth {
  -webkit-animation-delay: 1s;
  -moz-animation-delay: 1s;
  animation-delay: 1s;
}

/* Simple CSS3 Fade-in Animation */
.underlineHover:after {
  display: block;
  left: 0;
  bottom: -10px;
  width: 0;
  height: 2px;
  background-color: #56baed;
  content: "";
  transition: width 0.2s;
}

.underlineHover:hover {
  color: #0d0d0d;
}

.underlineHover:hover:after{
  width: 100%;
}



/* OTHERS */

*:focus {
    outline: none;
} 

#icon {
  width:60%;
}
a{
  text-decoration: none;
}
* {
  box-sizing: border-box;
}
    </style>
</head>
<body>
    <div class="wrapper fadeInDown">
        <div id="formContent">
          <!-- Tabs Titles -->
          <h2 class="active"><a href="" style="text-decoration: none;">Sign In</a> </h2>
          <h2 class="inactive underlineHover"> <a href="{% url 'register' %}" style="text-decoration: none;">Sign Up</a> </h2>

      
          <!-- Icon -->
          <div class="fadeIn first">
          </div>
      
          <!-- Login Form -->
          <!-- <form method="POST">
                {% csrf_token %}
                <div class="container" p> -->
                  <!-- {{form|crispy}} -->
                  <!-- <input type="submit" class="fadeIn fourth" value="Sign In"> -->
          <!-- </form> -->

          <form action="" method="POST">
            {% csrf_token %}
            {{form|crispy}}
            <input type="submit" class="fadeIn fourth" value="Sign In">

          </form>
    
          <!-- Remind Passowrd -->
          <div id="formFooter">
            <p>Don't have an account yet? <a class="underlineHover" href="{% url 'register' %}">Register </a></p>
          </div>
      
        </div>
      </div>
</body>
</html>
{% endblock content %}

csteusers/templates/csteusers/logout.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}

<div class="container margin-top margin-bottom">
    <h3 id="logoutid1">You have been logged out!!</h3>
    <div>
        <a id="fa" href="{% url 'signin' %}">
        <button class="btn btn-primary" id="logout-btn">
            LOGIN
        </button>
        </a>

    </div>
</div>

{% endblock content %}

csteusers/templates/csteusers/profile.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<!-- Main -->
<div class="container margin-top margin-bottom">
    <div class="container d-flex justify-content-end">
        <a href="{% url 'cstebase:question-create' %}">
            <div class="btn btn-primary">
                Ask a question
            </div>
        </a>
    </div>
    <h2>Profile</h2>
    <div class="card p-3">
        <div class="card-body">
            <table>
                <tbody>
                    <tr>
                        <img height="300px" width="auto" src="{{ user.profile.image.url }}" alt="profile image">
                    </tr>
                    <tr>
                        <td>Username</td>
                        <td>:</td>
                        <td>{{ user.username }}</td>
                    </tr>
                    <tr>
                        <td>Email</td>
                        <td>:</td>
                        <td>{{ user.email }}</td>
                    </tr>
                    <tr>
                        <td>Bio</td>
                        <td>:</td>
                        <td>{{ user.profile.bio|title }}</td>
                    </tr>
                    <tr>
                        <td>First Name</td>
                        <td>:</td>
                        <td>{{ user.profile.first_name }}</td>
                    </tr>
                    <tr>
                        <td>Last Name </td>
                        <td>:</td>
                        <td>{{ user.profile.last_name }}</td>
                    </tr>
                    <tr>
                        <td>Birth Day</td>
                        <td>:</td>
                        <td>{{ user.profile.birthday }}</td>
                    </tr>
                    <tr>
                        <td>Phone</td>
                        <td>:</td>
                        <td>{{ user.profile.phone|title }}</td>
                    </tr>
                    <tr>
                        <td>Linked in</td>
                        <td>:</td>
                        <td>{{ user.profile.linkedIn|title }}</td>
                    </tr>

                </tbody>

            </table>
        </div>

        <div class="row">
            <div class="col">
                <a href="{% url 'profile_update'  %}">
                    <div class="btn btn-success">
                        Update Profile
                    </div>
                </a>
            </div>
            <div class="col">
                <a href="{% url 'cstebase:ShowAllQuestionProfileBased' user.username %}">
                    <div class="btn btn-primary">
                        Show all Question
                    </div>
                </a>
            </div>
        </div>



    </div>

</div>
{% endblock content %}

csteusers/templates/csteusers/profile_update.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}

<div style="margin-top:100px ;margin-bottom:100px" class="container">
    <form action="" method="POST" enctype="multipart/form-data">

        {% csrf_token %}
        {{p_form|crispy}}
        {{image_form.image}}
        <p>
            <button class="btn btn-success mt-4" id="logout-btn" type="submit">Update
                Profile
            </button>
        </p>
    </form>
</div>

{% endblock content %}