CsteOverflow/urls.py
from re import template
from django.contrib import admin
from django.urls import path, include
from csteusers import views as user_view
from django.contrib.auth import views as auth_view
from django.conf import settings
from django.conf.urls.static import static
from cstebase import views
from csteusers.views import *
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('cstebase.urls')),
    
    # Authentication System
    # path('register/',user_view.register,name='register'),
    # path('login/',auth_view.LoginView.as_view(template_name='csteusers/login.html'),name='login'),
    path('logout/',auth_view.LogoutView.as_view(template_name='csteusers/logout.html'),name='logout'),
    
    #email authentications
    path('signup/',user_view.signup,name='signup'),
    path('signin/',user_view.signin,name='signin'),
    path('activate/<uidb64>/<token>',activate,name='activate'),
    
    # Profile 
    path('profile/',user_view.profile,name= "profile" ),
    path('profile/update',user_view.profile_update,name= "profile_update" ),
    # path('ckeditor/', include('ckeditor_uploader.urls')),
    # path('authentication/',include('csteusers.urls'))
    
    
    
] 
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

cstebase/urls.py
from re import template
from django.urls import path
from . import views



app_name = 'cstebase'

urlpatterns = [
    path('',views.Home.as_view(),name='home'),
    
    
    # CRUD Function
    path('questions/',views.QuestionListView.as_view(),name='question-lists'),
    path('questions/new/',views.QuestionCreateView.as_view(),name='question-create'),
    path('questions/<int:pk>',views.questionDetailedView,name='question-detail'),
    path('questions/<int:pk>/update',views.QuestionUpdateView.as_view(),name='question-update'),
    path('answered/<int:pk1>/<int:pk>',views.answeredQuestion,name='answered-question'),

    path('questions/<int:pk>/delete',views.QuestionDeleteView.as_view(),name='question-delete'),
    path('questions/<int:pk>/comment',views.AddCommentView,name='question-comment'),
    path('questions/<int:pk>/edit-answer/<int:comment_id>',views.EditCommentView,name='EditCommentView'),
    path('questions/<int:pk>/delete-answer/<int:comment_id>',views.DeleteCommentView,name='DeleteCommentView'),
    # path('questions/<int:pk>/comment',views.AddCommentView.as_view(),name='question-comment'),
    path('like/<int:pk>', views.like_view, name="like_post"),
    path('showprofile/<str:str>', views.ShowProfile,name='show_profile'),
    path('questions-all/<str:str>', views.ShowAllQuestionProfileBased,name='ShowAllQuestionProfileBased'),
    #path('all-question', views.ShowAllQuestionProfileBased, name="ShowAllQuestionProfileBased"),
    path('about/',views.About_page,name='about'),
    path('tags/<slug:tag_slug>',views.TagListView.as_view(),name="post_tag"),
    # path('test/',views.test.as_view(),name="test"),
    path('tags/',views.AllTags,name="tags"),
    path('questions/search/',views.search,name='search'),
]
    

    

cstebase/models.py
from turtle import title
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse 
from ckeditor.fields import RichTextField
from ckeditor_uploader.fields import RichTextUploadingField
from taggit.managers import TaggableManager



class Question(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=10000,unique=True)
    content = RichTextField()
    # content = models.TextField(null=True, blank=True)
    likes = models.ManyToManyField(User, related_name='question_post')
    date_created = models.DateTimeField(default=timezone.now)   
    anonymous = models.BooleanField(default=False)
    # answered = models.BooleanField(default=False)
    tags = TaggableManager()
    
    
    
    def __str__(self):
        return f'{self.title}'
    
    def get_absolute_url(self):
        return reverse('cstebase:question-detail', kwargs={'pk':self.pk})
    
    def total_likes(self):
        return self.likes.count()


class Comment(models.Model):
    question = models.ForeignKey(Question,related_name="comment", on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    content = RichTextField()
    date_created = models.DateTimeField(default=timezone.now)
    answered = models.BooleanField(default=False)
    
    def __str__(self):
        return f'%s - %s ' % (self.question.title,self.question.user)
    
    def get_absolute_url(self):
        return reverse('cstebase:question-detail', kwargs={'pk':self.pk})
    
    def save(self ,*args,**kwargs):
        super().save(*args,**kwargs)
        
class AboutPage(models.Model):
    name = models.CharField( max_length=50)
    title = models.CharField( max_length=50)
    about = RichTextField()
    image  = models.ImageField( upload_to='about/', height_field=None, width_field=None, max_length=None)
    def __str__(self):
        return self.name



class teamMember(models.Model):
    name = models.CharField( max_length=50)
    title = models.CharField( max_length=50)
    about = models.TextField()
    image  = models.ImageField( upload_to='teamMember/', height_field=None, width_field=None, max_length=None)
    def __str__(self):
        return self.name

cstebase/forms.py
from tkinter import Widget
from .models import Comment, Question
from django import forms 
from taggit.models import Tag 

class CommentForm(forms.ModelForm):
    
    class Meta:
        model = Comment
        fields = ['content']
        
        widgets = {
             'content' : forms.Textarea(attrs={'class':'form-control'}) ,
             
        }
class QuestionForm(forms.ModelForm):
    tags = forms.ModelMultipleChoiceField(label='Tags', queryset=Tag.objects.order_by('name'),widget=forms.SelectMultiple)

    class Meta:
        model = Question
        fields = ['title', 'content','anonymous',"tags"]
        
        widgets = {
             'title' : forms.TextInput(attrs={'class':'form-control '}),
             'content' : forms.Textarea(attrs={'class':'form-control'}),             
        }

cstebase/views.py
from multiprocessing import context
from turtle import title
from urllib import request
from django.shortcuts import render,get_object_or_404,redirect
from django.views.generic import ListView,DetailView,CreateView,UpdateView,DeleteView,TemplateView
from csteusers.views import profile
from .models import Question,Comment ,teamMember,AboutPage
from .forms import *
from django.urls import reverse_lazy,reverse
from django.contrib.auth.mixins import LoginRequiredMixin,UserPassesTestMixin
from django.http import HttpResponseRedirect 
from django.core.paginator import Paginator, EmptyPage
from csteusers.models import Profile
from django.contrib.auth.models import User
from taggit.models import Tag 
from django.db.models import Q
#home
def home(request):
    about_member = teamMember.objects.all

    context={
        'about_member':about_member,

    }
    return render(request,'home.html',context)


def AllTags(request):
    tags = Tag.objects.filter().order_by('name')
    context = {
        'tags':tags 
    }
    return render(request,'cstebase/tags.html',context)
    
    

class Home(ListView):
    model = Question
    context_object_name = 'questions'
    ordering = ['-date_created']
    template_name = 'home.html'
    
    
class TagListView(ListView):
    model = Question
   
    template_name = "question_list.html"
    context_object_name = "questions"

    
    def get_queryset(self):
        return Question.objects.filter(tags__slug=self.kwargs.get('tag_slug')).order_by('-date_created')
    
# CRUD

def like_view(request, pk):
    question = Question.objects.get(id = pk)
    if question.likes.filter(id = request.user.id).exists():
        question.likes.remove(request.user)
    else:
        question.likes.add(request.user)
    
    return HttpResponseRedirect(reverse('cstebase:question-detail', args=[str(pk)]))



class QuestionListView(ListView):
    model = Question
    context_object_name = 'questions'
    ordering = ['-date_created']
    paginate_by = 2
    #paginator_class = MyPaginator # We use our paginator class 
    tags = Tag.objects.all 
    context ={
            'tags':tags
        }

    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        
        search_input = self.request.GET.get('search-area') or ""
        if search_input:
            context['questions'] = Question.objects.filter(Q(title__icontains = search_input))
            context['search_input'] = search_input 
        # Pagination
        
        
        
        return context


class QuestionDetailView(DetailView):
    model = Question

    def get_context_data(self, *args, **kwargs):
        context = super(QuestionDetailView, self).get_context_data()
        something = get_object_or_404(Question, id=self.kwargs['pk'])
        total_likes = something.total_likes()
        liked = False
        if something.likes.filter(id=self.request.user.id).exists():
            liked = True

        context['total_likes'] = total_likes
        context['liked'] = liked
        return context
    
def questionDetailedView(request,pk):
    question = Question.objects.get(id = pk)
    form_comment = CommentForm(request.POST or None)
    total_likes = question.likes.count()
    try:
        liked = question.likes.filter(id = request.user.id).exists()
    except:
        liked = False
    if request.method == "POST":
        if form_comment.is_valid():
            form_comment = form_comment.save(commit=False)
            form_comment.user = request.user
            form_comment.question = question
            form_comment.save()
            return redirect('cstebase:question-detail',pk)
    context={
        'question':question,
        'form_comment':form_comment,
        'total_likes':total_likes,
        'liked':liked,
    }
    return render(request,'cstebase/question_detail.html',context)

 


class QuestionCreateView(LoginRequiredMixin,CreateView):
    model = Question
    form_class = QuestionForm
    #fields = ['title', 'content','anonymous']

    context_object_name =  'question'

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)
    
    
    
class test(LoginRequiredMixin,CreateView):
    model = Question
    form_class = QuestionForm
    #fields = ['title', 'content','anonymous']
    template_name = "cstebase/test.html"

    context_object_name =  'question'
    def get_context_data(self, **kwargs):
        context = super(test, self).get_context_data(**kwargs)
        context['tags'] = Tag.objects.all().order_by('name')
        # Add any other variables to the context here
        ...
        return context

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)
    
   


class QuestionUpdateView(UserPassesTestMixin, LoginRequiredMixin, UpdateView):
    model = Question
    #fields = ['title', 'content','anonymous']
    tags = Tag.objects.all()
    context ={
            'tags':tags
        }
    form_class = QuestionForm
    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

    def test_func(self):
        questions = self.get_object()
        if self.request.user == questions.user:
            return True
        return False


class QuestionDeleteView(UserPassesTestMixin,LoginRequiredMixin,DeleteView):
    model = Question
    context_object_name ='question'
    # template_name = "TEMPLATE_NAME"
    success_url = '/'
    def test_func(self):
        questions = self.get_object()
        if self.request.user == questions.user:
            return True
        return False
    
def answeredQuestion(request,pk1,pk):
    answered =  Comment.objects.get(id = pk)
    if answered.answered :
        answered.answered = False
    else:
        answered.answered = True
        
    answered.save()
    return redirect('cstebase:question-detail',pk1)
    


class CommentDetailView(CreateView):
    model = Comment
    form_class = CommentForm
    template_name = 'cstebase/question-detail.html'
    
    def form_valid(self, form):
        form.instance.question_id = self.kwargs['pk']
        return super().form_valid(form)
    success_url = reverse_lazy('cstebase:question-detail')

def AddCommentView(request,pk):
    question = Question.objects.get(id=pk)
    
    form  = CommentForm()
    if request.method =="POST":
        form  = CommentForm(request.POST ,request.FILES )
        if form.is_valid():
            comment = form.save(commit=False)
            comment.user = request.user
            comment.question = question
            comment.save()
            return redirect('cstebase:question-detail',pk)
        
    context = {
        "form":form
    }
    return render(request,'cstebase/question-answer.html',context)
    
def EditCommentView(request,pk,comment_id):
    comment = Comment.objects.get(id=comment_id)
    question = Question.objects.get(id=pk)
    
    
    form  = CommentForm(instance=comment)
    if request.method =="POST":
        form  = CommentForm(request.POST ,request.FILES, instance=comment)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.save()
            return redirect('cstebase:question-detail',pk)
        
    context = {
        "form":form
    }
    return render(request,'cstebase/question-answer.html',context)
   
    
def DeleteCommentView(request,pk,comment_id):
    comment = Comment.objects.get(id=comment_id)
    question = Question.objects.get(id=pk)
    if request.method =="POST":
        comment.delete()
        return redirect('cstebase:question-detail',pk)
        
    context = {
        "comment":comment,
        "question":question,
    }
    return render(request,'cstebase/question_confirm_delete.html',context)
   
    


#Show Profile
def ShowProfile(request,str):
    #ShowProfile = Profile.objects.filter( user = str )
    ShowProfile = get_object_or_404(User,username = str )
    
    #ShowProfile = get_object_or_404(Profile,user = pk )
    context = {
        'ShowProfile' :ShowProfile
    }
    return render(request,'cstebase/profile_page.html',context)



def ShowAllQuestionProfileBased(request,str):
    questions = Question.objects.filter(user__username = str).order_by('-date_created')
    # questions = Question.objects.filter(user = str)
    paginator = Paginator(questions,2)
    page = request.GET.get("page")
    paged_products = paginator.get_page(page)
    context = {
        'questions':paged_products,
        'page_obj':paged_products
    }
    return render(request,'cstebase/question_list_profile.html',context)


def About_page(request):
    nstu = 'About NSTU'
    vc = 'Vice Chancellor'
    about_member = teamMember.objects.all
    # about_nstu = About.objects.get()
    about_nstu = AboutPage.objects.get(title=nstu)
    about_vc = AboutPage.objects.get(name=vc)
    context={
        'about_member':about_member,
        'about_nstu':about_nstu,
        'about_vc':about_vc
    }
    
    
    return render(request,'cstebase/about.html',context)


def search(request):
   if 'keyword' in request.GET:
      keyword = request.GET['keyword'] 
      
      print("helllo ",keyword)
      if keyword:
         keyword = Question.objects.order_by('-date_created').filter(title__icontains=keyword)
         keyword_count = keyword.count()
         
      else:
          keyword_count = 0
         
      context = {
         'questions':keyword,
          'keyword_count':keyword_count,
      }
   return render(request,'cstebase/question_list.html',context)

cstebase/templates/cstebase/question_detail.html
{% extends 'base.html' %}
{% block content %}
{% load static %}

<div class="container card_container">

     <div class="card">
          <div class="card-header">
               <h5>{{question.title}}</h5>
               <h6>
                    Asked by:
                    {% if question.anonymous == True %}
                    <a href="">Anonymous</a>
                    {% else %}

                    <a href="{% url 'cstebase:show_profile' question.user.username  %} "><img
                              style="height:50px;width:50px;border-radius:50%" src="{{question.user.profile.image.url}}"
                              alt=""> {{ question.user.profile.first_name }} {{ question.user.profile.last_name }}</a>
                    {% endif %}
                    <br>
                    Created At: {{ object.date_created|date:"j F, Y" }}
                    <br>

                    <i class="fa fa-tags"></i>:
                    {% for tag in question.tags.all %}
                    <a href="{% url 'cstebase:post_tag' tag.slug %}">{{tag.name}},</a>
                    {% endfor %}
               </h6>
          </div>



          <div class="card-body card-body-detail">
               <p class="card-text">{{question.content|safe}}</p>
               <br>
               <form action="{% url 'cstebase:like_post' question.id %}" method="POST">
                    {% csrf_token %}
                    {% if user.is_authenticated %}
                    {% if liked %}
                    <div style="display: flex; align-items: center; margin-left: 10px;">
                         <button type="submit" name="question_id" value="{{ question.id }}"
                              style="border: none; border-radius: 60px;"><img src="{% static 'image/Dislike.png' %}"
                                   alt="" style="width: 40px;"></button>
                         <h5 style="margin-left: 10px; cursor: pointer;"> | {{ total_likes }} Likes</h5>
                    </div>
                    {% else %}
                    <div style="display: flex; align-items: center; margin-left: 10px;">
                         <button type="submit" name="question_id" value="{{ question.id }}"
                              style="border: none; border-radius: 30px;"><img src="{% static 'image/like.png' %}" alt=""
                                   style="width: 40px;"></button>
                         <h5 style="margin-left: 10px; cursor: pointer;"> | {{ total_likes }} Likes</h5>
                    </div>
                    {% endif %}
                    {% else %}
                    <h5 style="margin-left: 10px; cursor: pointer;"><a href="{% url 'signin' %}">Login</a>
                         to
                         Like Question | {{ total_likes }} Likes</h5>
                    {% endif %}

               </form>
               {% if user.id == question.user.id %}

               <a style="text-decoration: none; " class="btn btn-outline-success"
                    href="{% url 'cstebase:question-update' question.id %}">&#x270E;</a>
               <a style="text-decoration: none; " class="btn btn-outline-danger"
                    href="{% url 'cstebase:question-delete' question.id %}">&#x2716;</a>
               {% endif %}

               <a style="text-decoration: none; " class="btn btn-outline-secondary"
                    href="{% url 'cstebase:question-lists' %}">&#x21a9;</a>
          </div>
          {% with question.comment.count as total_comments %}
          <legend class="border-bottom mb-4">{{total_comments }}
               comment{{total_comments|pluralize }}</legend>
          {% endwith %}
          <h2>Answers</h2> <br><br><br>
          {% for comment in question.comment.all %}
          {% if comment.answered is True %}

          <div class="container">
               <ul>
                    <li>
                         <div class="container">
                              <h3 style="font-weight: normal; font-size: 15px;">{{comment.content|safe}}</h3>
                              <h3 style="font-size: 10px;">Answered by: <i><a href="">{{comment.user}}</a> - On:
                                        {{comment.date_created|date:"j F, Y"}}</i>
                                   <img src="{% static 'image/check-mark.png' %}" style='width:40px' alt="">

                                   {% if user.is_authenticated %}
                                   {% if request.user ==  question.user %}
                                   <a href="{% url 'cstebase:answered-question' question.id  comment.id %}">

                                        <div class="btn btn-danger">Wrong</div>
                                   </a>
                                   {% endif %}
                                   {% if request.user ==  comment.user %}
                                   <a href="{% url 'cstebase:DeleteCommentView' question.id  comment.id %}">
                                        <div class="btn btn-danger">
                                             Delete Answer
                                        </div>
                                   </a>
                                   <a target="_blank"
                                        href="{% url 'cstebase:EditCommentView' question.id  comment.id %}">
                                        <div class="btn btn-success">
                                             Edit Answer
                                        </div>
                                   </a>
                                   {% endif %}
                                   {% endif %}
                              </h3>
                              <hr>
                         </div>

                    </li>
               </ul>
          </div>
          {% endif %}
          {% endfor %}


          {% if not question.comment.all %}
          <h3>No Answers yet... </h3>
          {% else %}
          {% for comment in question.comment.all %}

          {% if comment.answered is False %}

          <div class="container">


               <h3 style="font-weight: normal; font-size: 15px;">{{comment.content|safe}}</h3>

               <h3 style="font-size: 10px;">Answered by: <i><a
                              href="{% url 'cstebase:show_profile' comment.user  %}">{{comment.user.profile.first_name}}
                              {{comment.user.profile.last_name}}</a> - On:
                         {{comment.date_created|date:"j F, Y"}}</i>
                    {% if user.is_authenticated %}
                    {% if request.user ==  question.user %}
                    <a href="{% url 'cstebase:answered-question' question.id  comment.id %}">
                         <div class="btn btn-primary">Correct</div>
                    </a>

                    {% endif %}
                    {% if request.user ==  comment.user %}
                    <a href="{% url 'cstebase:DeleteCommentView' question.id  comment.id %}">
                         <div class="btn btn-danger">
                              Delete Answer
                         </div>
                    </a>
                    <a target="_blank" href="{% url 'cstebase:EditCommentView' question.id  comment.id %}">
                         <div class="btn btn-success">
                              Edit Answer
                         </div>
                    </a>
                    {% endif %}
                    {% endif %}

               </h3>
               <hr>
          </div>
          {% endif %}
          {% endfor %}
          {% endif %}
          {% comment %} <a target="_blank" class="btn btn-outline-primary" id="fa"
               href="{% url 'cstebase:question-comment' question.id %}" style="text-decoration: none;">Answer
               Question
          </a> {% endcomment %}

          <p>
               <button class="btn btn-outline-primary" type="button" data-bs-toggle="collapse"
                    data-bs-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
                    Answer the Question
               </button>
          </p>
          <div class="collapse" id="collapseExample">
               <div class="card card-body">
                    <div class="container mt-5 mb-5">

                         <form action="" method="POST">
                              {% csrf_token %}
                              <h2>Answer</h2>
                              {{form_comment.content}}
                              {{ form_comment.media }}
                              <br>
                              <button class="btn btn-success" id="logout-btn" type="submit">Post Answer </button>
                              <a style="text-decoration: none; " class="btn btn-outline-secondary"
                                   href="{% url 'cstebase:question-lists'%} ">Cancel</a>
                         </form>
                    </div>
               </div>
          </div>



     </div>
</div>

{% endblock content %}

cstebase/templates/cstebase/question_form.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/bbbootstrap/libraries@main/choices.min.css">
<script src="https://cdn.jsdelivr.net/gh/bbbootstrap/libraries@main/choices.min.js"></script>

<div class="container">

     <form style="margin-top:150px" action="" method="POST" enctype="multipart/form-data">
          {% csrf_token %}
          <h3>Title </h3>
          <h6>Be specific and imagine you're asking a question to another person</h6>
          {{form.title}}
          <br>
          <h3>Body </h3>
          {{form.content}}

          <h3>Tags</h3>

          <h6>
               <a target="_blank" href="{% url 'cstebase:tags' %}">Show all tags</a></h6>
          <br>
          {{form.tags}}
          <h3>If you want to hide your identity please check it on. </h3>
          [<input class="form-check-input" type="checkbox" name="anonymous" id="id_anonymous">]
          {{ form.media }}
          <br>
          <div class="container m-3">

               {% if question.id is none %}
               <button class="btn btn-success" id="logout-btn" type="submit">Post
                    Question</button>
               <button class="btn btn-secondary" id="logout-btn" type="submit"><a id="fa"
                         href="{% url 'cstebase:question-lists' %}" style="color: white; text-decoration: none;">Go
                         back</a></button>
               {% else %}
               <button class="btn btn-success" id="logout-btn" type="submit">
                    Update Question</button>
               <a style="text-decoration: none; " class="btn btn-outline-secondary"
                    href="{% url 'cstebase:question-detail' question.id %}">Cancel</a>
               {% endif %}
          </div>
     </form>
     <script>
          $(document).ready(function () {

               var multipleCancelButton = new Choices('#id_tags', {
                    removeItemButton: true,
                    maxItemCount: 5,
                    searchResultLimit: 5,
                    renderChoiceLimit: 5
               });

          });
     </script>
</div>




{% endblock content %}

cstebase/templates/cstebase/question_list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container_blogpost container ">
    <div id="container ">

        {% if 'search' in request.path %}
        {% if keyword_count %}

        <h1 id="fh1"> <b> {{keyword_count}}</b> Questions Found </h1>
        {% else %}
        <h2>0 Found</h2>
        {% endif %}
        {% else %}
        <h1>Top Questions</h1>
        {% endif %}

        {% if user.is_authenticated %}
        <a href="{% url 'cstebase:question-create' %}"><button class="btn btn-primary" id="logout-btn">Ask
                Question</button></a>
        {% else %}
        <a href="{% url 'signin' %}"><button class="btn btn-primary">Ask Question</button></a>
        {% endif %}
    </div>

    {% for question in questions  %}
    <div class="blog_post mt-5 mb-5 ">
        <div class="img_pod">
            {% if question.anonymous == True %}
            <img class="blog-img" src="{% static 'image/default.jpg' %}" alt="random image">
            {% else %}

            <img class="blog-img" src="{{ question.user.profile.image.url }}" alt="random image">
            {% endif %}
        </div>
        <div class="container_copy">
            <h3>{{question.date_created|date:"j F, Y"}}</h3>
            <h1><a href="{% url 'cstebase:question-detail' question.id %}">{{ question.title }}</a></h1>
            Asked by:
            {% if question.anonymous == True %}
            <a href="">Anonymous</a>
            {% else %}

            <a href="{% url 'cstebase:show_profile' question.user.username  %}">{{ question.user|title }}</a>
            {% endif %}
            <h6>
                <i class="fa fa-tags"></i>:
                {% for tag in question.tags.all %}
                <a href="{% url 'cstebase:post_tag' tag.slug %}">{{tag.name}}</a>,
                {% endfor %}
            </h6>
            {% if question.content|wordcount <= 30 %}
            <p>{{ question.content|safe}}</p>
            {% else %}
            <p>{{ question.content|safe|truncatewords:30}}</p>
            <a class="btn_primary" href="{% url 'cstebase:question-detail' question.id %}">Read More</a>
            {% endif %}
        </div>

    </div>
    {% endfor %}

    <div class="d-flex justify-content-center">
        <nav aria-label="Page navigation example">
            <ul class="pagination justify-content-center">
                {% if page_obj.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page=1">First</a>
                </li>
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a>
                </li>
                <span class="current">
                    <li class="page-item"><a class="page-link"
                            href="?page={{ page_obj.number|add:"-1"}} ">{{ page_obj.number|add:"-1"  }}</a></li>
                </span>

                {% endif %}
                <span class="current">
                    <li class="page-item"><a class="page-link" href="">{{ page_obj.number }}</a></li>
                </span>
                {% if page_obj.has_next %}
                <span class="current">
                    <li class="page-item"><a class="page-link"
                            href="?page={{ page_obj.number|add:"1"}} ">{{ page_obj.number|add:"1"  }}</a></li>
                </span>
                <li class="page-item">
                    {% comment %} <a href="?page={{ page_obj.next_page_number }}">next</a>
                    <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a> {% endcomment %}
                    <a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a>
                </li>
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
                </li>
                {% endif %}
            </ul>
        </nav>
    </div>


</div>

{% endblock content %}

cstebase/templates/cstebase/tags.html
{% extends "base.html" %}
{% block content %}


<div style="margin:100px" class="container">
  <ol>

    {% for tag in tags %}


    <li style="font-size:2rem">
      <a href="{% url 'cstebase:post_tag' tag.slug %}">{{tag.name}}</a>
    </li>
    {% endfor %}
  </ol>
</div>


{% endblock content %}