CsteOverflow/urls.py
from re import template
from django.contrib import admin
from django.urls import path, include
from csteusers import views as user_view
from django.contrib.auth import views as auth_view
from django.conf import settings
from django.conf.urls.static import static
from cstebase import views
from csteusers.views import *
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('cstebase.urls')),
    
    # Authentication System
    # path('register/',user_view.register,name='register'),
    # path('login/',auth_view.LoginView.as_view(template_name='csteusers/login.html'),name='login'),
    path('logout/',auth_view.LogoutView.as_view(template_name='csteusers/logout.html'),name='logout'),
    
    #email authentications
    path('signup/',user_view.signup,name='signup'),
    path('signin/',user_view.signin,name='signin'),
    path('activate/<uidb64>/<token>',activate,name='activate'),
    
    # Profile 
    path('profile/',user_view.profile,name= "profile" ),
    path('profile/update',user_view.profile_update,name= "profile_update" ),
    # path('ckeditor/', include('ckeditor_uploader.urls')),
    # path('authentication/',include('csteusers.urls'))
    
    
    
] 
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

cstebase/urls.py
from re import template
from django.urls import path
from . import views



app_name = 'cstebase'

urlpatterns = [
    path('',views.Home.as_view(),name='home'),
    
    
    # CRUD Function
    path('questions/',views.QuestionListView.as_view(),name='question-lists'),
    path('questions/new/',views.QuestionCreateView.as_view(),name='question-create'),
    path('questions/<int:pk>',views.questionDetailedView,name='question-detail'),
    path('questions/<int:pk>/update',views.QuestionUpdateView.as_view(),name='question-update'),
    path('answered/<int:pk1>/<int:pk>',views.answeredQuestion,name='answered-question'),

    path('questions/<int:pk>/delete',views.QuestionDeleteView.as_view(),name='question-delete'),
    path('questions/<int:pk>/comment',views.AddCommentView,name='question-comment'),
    path('questions/<int:pk>/edit-answer/<int:comment_id>',views.EditCommentView,name='EditCommentView'),
    path('questions/<int:pk>/delete-answer/<int:comment_id>',views.DeleteCommentView,name='DeleteCommentView'),
    # path('questions/<int:pk>/comment',views.AddCommentView.as_view(),name='question-comment'),
    path('like/<int:pk>', views.like_view, name="like_post"),
    path('showprofile/<str:str>', views.ShowProfile,name='show_profile'),
    path('questions-all/<str:str>', views.ShowAllQuestionProfileBased,name='ShowAllQuestionProfileBased'),
    #path('all-question', views.ShowAllQuestionProfileBased, name="ShowAllQuestionProfileBased"),
    path('about/',views.About_page,name='about'),
    path('tags/<slug:tag_slug>',views.TagListView.as_view(),name="post_tag"),
    # path('test/',views.test.as_view(),name="test"),
    path('tags/',views.AllTags,name="tags"),
    path('questions/search/',views.search,name='search'),
]
    

    

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
     <meta charset="UTF-8">
     <meta http-equiv="X-UA-Compatible" content="IE=edge">
     <meta name="viewport" content="width=device-width, initial-scale=1.0">
     <title>CSTEOVERFLOW</title>
     <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
     <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"
          integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous">
     </script>
     <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css" />

     <link rel="stylesheet" href="{% static 'index.css' %} ">
     <link rel="preconnect" href="https://fonts.googleapis.com">
     <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
     <link href="https://fonts.googleapis.com/css2?family=Abhaya+Libre:wght@700&family=Alegreya&family=Merriweather&display=swap"
          rel="stylesheet">
     <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.js">
     </script>

     <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.16/jquery-ui.js">
     </script>

     <link href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.16/themes/ui-lightness/jquery-ui.css"
          rel="stylesheet" type="text/css" />
     <style>

     </style>

</head>

<body>
     <nav class="navbar navbar-expand-lg bg-body-tertiary bg-dark navbar-static-top navbar-default fixed-top"
          data-bs-theme="dark">
          <div class="container-fluid ">
               <a class="navbar-brand" href="/">CSTEOVERFLOW</a>
               <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
               </button>
               <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                         <li class="nav-item">
                              <a class="nav-link active" aria-current="page" href="{% url 'cstebase:about' %}">About</a>
                         </li>
                         <li class="nav-item">
                              <a class="nav-link active" aria-current="page"
                                   href="http://127.0.0.1:8000/about/#contributor">For Teams</a>
                         </li>

                    </ul>
                    <form action="{% url 'cstebase:search' %}" method="GET" class="d-flex" role="search">
                         <input class="form-control me-2" name='keyword' type="search" placeholder="Search"
                              aria-label="Search">
                         <button class="btn btn-outline-success" type="submit">Search</button>
                    </form>
                    <ul class="navbar-nav  mb-2 mb-lg-0">
                         {% if user.is_authenticated %}
                         <li class="nav-item">
                              <a class="nav-link active" aria-current="page" href="{% url 'profile' %}">Profile</a>
                         </li>
                         <li class="nav-item">
                              <a class="nav-link active" aria-current="page" href="{% url 'logout' %}">Logout</a>
                         </li>
                         {% else %}
                         <li class="nav-item">
                              <a class="nav-link active" aria-current="page" href="{% url 'signin' %}">Sign in</a>
                         </li>
                         <li class="nav-item">
                              <a class="nav-link active" aria-current="page" href="{% url 'signup' %}">Sign up</a>
                         </li>

                         {% endif %}
                    </ul>
               </div>
          </div>
     </nav>
     
     {% if messages %}
          
     <div class="container margin-top">
          {% for message in messages %}
          <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
               <strong>{{ message }}</strong> 
               <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
          </div>
          {% endfor %}
     </div>
     {% endif %}
          
     {% block content %}

     {% endblock content %}



     <footer class="bg-dark text-light py-3">
          <div class="container d-flex justify-content-center">
               <div class="footer-links-title nav-link">Cste Overflow</div>
          </div>
          <div class="container d-flex justify-content-center">
               <p style="color:white">2022 Copyright: Noakhali Science and Technology University (NSTU)
               </p>
          </div>
     </footer>


</body>

</html>

templates/home.html
{% extends 'base.html' %}
{% block content %}

<div class="main-bg ">
    <div class="container p-5">

        <h1 class="hero-title ">Welcome to </h1>
        <div style="color:#D4D925" class="waviy">
            <div class="waivyfirst">

                    <span style="--i:1 ;color:#5CB8E4">C</span>
                    <span style="--i:2;color:#5CB8E4">S</span>
                    <span style="--i:3;color:#5CB8E4">T</span>
                    <span style="--i:4;color:#5CB8E4">E</span>
            </div>
            <div class="waivysecond">

                    <span style="--i:5;color:#5CB8E4">O</span>
                    <span style="--i:6;color:#5CB8E4">V</span>
                    <span style="--i:7;color:#5CB8E4">E</span>
                    <span style="--i:8;color:#5CB8E4">R</span>
                    <span style="--i:9;color:#5CB8E4">F</span>
                    <span style="--i:10;color:#5CB8E4">L</span>
                    <span style="--i:11;color:#5CB8E4">O</span>
                    <span style="--i:12;color:#5CB8E4">W</span>
            </div>
        </div>

    </div>
    <div class="container d-flex justify-content-center">
        <a href="{% url 'cstebase:question-lists' %}">

            <div class="btn btn-outline-primary">Latest Question</div>
        </a>
    </div>
</div>

{% endblock content %}